spring:
  config:
    activate:
      on-profile: "docker"
    import:
      - secret.yml
      - oauth.yml
  application:
    name: auth-service

  redis:
    host: redis
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://eureka:8761/eureka